## IWU - Gradtagzahlen Deutschland - Shiny App
Version: 11.10.2024

## Erläuterungen 

Mit dieser Shiny-App können für einen spezifischen Standort Monatswerte für Klimadaten ermittelt werden, die in der energetischen Bilanzierung und bei der Klimabereinigung verwendbar sind. Die App umfasst einen Teil der Funktionalität des Excel-Tools 'Gradtagzahlen-Deutschland.xlsx'. Das Tool wurde im Kontext des Forschungsprojektes MOBASY erstellt. 

Als Quelle für die Klimadaten werden folgende Daten des Deutschen Wetterdienstes DWD verwendet: 

- Tagesmittel der Außentemperatur für über 800 DWD-Klimstationen (https://opendata.dwd.de/) 

- Monatswerte für die Globalstrahlung auf horizontale Flächen (https://cmsaf.eu)


Diese DWD-Daten wurden zu Monatsdaten an Heiztagen weitererarbeitet, zusätzlich wurden mit Hilfe von Schätzfunktionen  Monatswerte der Globalstrahlung (Summe Monat und an Heiztagen im Monat) für unterschiedliche Orientierungen ermittelt. Die so weiterverarbeiteten Daten stehen im R-Datenpaket clidamonger auf CRAN zur Verfügung. Dieses Paket wird von dem vorliegenden Tool genutzt. 

Für die Ermittlung der Klimadaten für eine gegebene Postleitzahl wird das R-Paket CliDaMon verwendet (https://github.com/TobiasLoga/CliDaMon). Da im R-Skript die Aggregation und Mittelwertbildung etwas anders funktioniert als in dem oben erwähnten Excel-Tool 'Gradtagzahlen-Deutschland.xlsx' können die Ergebnisse leicht von einander abweichen.   

Wir stellen das Werkzeug gerne anderen Experten zur Nutzung Verfügung, können jedoch keinerlei Support übernehmen. Wir übernehmen keine Gewähr für die Vollständigkeit, Richtigkeit und Genauigkeit der Berechnungen und der Daten. Fehler können gemeldet werden an: Tobias Loga t.loga@iwu.de


### Erläuterung der Variablen 

- **D [d] Tage (days)** <br>
   Länge der betrachteten Periode

- **TA [°C] Außenlufttemperatur (air temperature)**

- **HD [d] Heiztage (heating days)**  <br>
   Heiztage sind Tage an denen die über den Tag gemittelte Außenlufttemperatur unter der Heizgrenztemperatur liegt.

- **HDD [Kd] Heizgradtage (heating degree days)** <br>
   Zur Ermittlung der Heizgradtage eines Monats werden die an Heiztagen auftretenden Differenzen zwischen der Heizgrenztemperatur und dem Tagesmittel der Außenlufttemperatur erfasst und aufsummiert.

- **RHDD [Kd] Gradtagzahlen	(room heating degree days)** <br>
   Zur Ermittlung der Gradtagszahl eines Monats werden die an Heiztagen auftretenden Differenzen zwischen der Raumtemperatur und dem Tagesmittel der Außenlufttemperatur erfasst und aufsummiert.

- **CT [-] Indikator für die Vollständigkeit (completeness indicator)** <br>
   Der Indikator kann im Prinzip Werte zwischen 0,00 und 1,00 annehmen. Ein Wert von 0,95 bedeutet beispielsweise, dass für 5% des Zeitraums keine Messdaten für die Außentemperatur vorliegen (Messdatenausfälle der Wetter-Stationen). 

- **G_Hor, G_E, G_S, G_W, G_N [kWh] Globalstrahlung auf unterschiedliche Orientierungen** <br>
   Monatswerte bzw. Jahreswerte Globalstrahlung; Orientierung der Flächen horizontal sowie vertikal Ost, Süd, West, Nord

- **G_Hor_HD, G_E_HD, G_S_HD, G_W_HD, G_N_HD [kWh] Globalstrahlung an Heiztagen** <br>
  Monatswerte bzw. Jahreswerte Globalstrahlung an Heiztagen; Orientierung der Flächen horizontal sowie vertikal Ost, Süd, West, Nord


### Gradtagzahl oder Heizgradtage - Welchen Wert wofür verwenden?										

Die Gradtagzahl ist die richtige Eingangsgröße für eine Energiebilanzrechnung, bei der innerhalb der Heizperiode solare und interne Gewinne mit berücksichtigt werden, wodurch sich der Wärmebedarf entsprechend reduziert.										
Heizgradtage sind der geeignete Vergleichswert um für gemessene Verbräuche eine Klimabereinigung vorzunehmen. Dabei wird der Verbrauchswert durch die entsprechenden Heizgradtage geteilt, woduch sich ein Wärmebedarf pro Temperaturdifferenz ergibt. Durch den Vergleich dieser Werte für mehrere Heizperioden lässt sich feststellen, ob sich ein Verbrauchswert klimabereinigt vermindert oder erhöht hat.


### Welches Gebäude hat welche Heizgrenze?										

Je besser der Wärmeschutz eines Gebäudes ist, um so niedriger liegt die Heizgrenztemperatur. 								

Im Folgenden sind Anhaltswerte für die Heizgrenztemperatur genannt:			

|  Baustandard	         | Heizgrenze |
|  --------------------- | ---------- |
|  Bestandsgebäude	     |   15,0 °C  |								
|  Niedrigenergiehäuser	 |   12,0 °C	|					
|  Passivhäuser	         |   10,0 °C  |						


Diese Heizgrenztemperaturen gelten für Standardansätze des Klimas und der Nutzung (z.B. Raumtemperatur 20°C). Die tatsächliche Heizgrenztemperatur eines Gebäudes kann jedoch deutlich davon abweichen. Gegenüber den genannten Zahlenwerten erhöhte Werte können sich beispielsweise bei höheren Raumtemperaturen oder bei starker Verschattung der Fenster ergeben. 		

Quelle für die Temperaturdaten						
						
	DWD - Deutscher Wetterdienst					
	www.dwd.de					
	CDC (Climate Data Center) DE					
	https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/daily/kl/historical/					
	Data base: 		Daily temperatures			
	Variable:		TMK			


Quelle für die Solarstrahlungsdaten						
						
	DWD - Deutsche Wetterdienst					
	EUMETSAT  / Satellite Application Facility on Climate Monitoring (CM SAF)					
	www.cmsaf.eu					
	Variable:		SIS			

-----

Logbuch der Änderungen						
						
  2024-08-26					
  
  Korrektur Tab 'Eingaben' / section 'Ergebnisse' / 'Klima 2 im Verhältnis zu Klima 1': Copy-paste-Fehler: Label war falsch für den Fall 'HDD' ('RHDD' statt 'HDD')					
	
						
  2024-10-11					
  
  Korrektur: Die Schätzung der Heiztage für Monate mit unvollständigen Temperaturmesswerten der Klimastationen musste korrigiert werden.					
  
  Verbesserung: Datentabellen haben jetzt Scrollbalken					    
						
-----


Institut Wohnen und Umwelt GmbH

Tobias Loga 									

www.iwu.de 
